name: FinanzApp
options:
  bundleIdPrefix: com.finanzapp
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "6C53L638P6"
    CODE_SIGN_STYLE: Automatic

targets:
  FinanzApp:
    type: application
    platform: iOS
    sources:
      - path: FinanzApp
        excludes:
          - "**/.DS_Store"
    info:
      path: FinanzApp/Info.plist
      properties:
        CFBundleDisplayName: FinanzApp
        CFBundleShortVersionString: 6.0.0
        LSRequiresIPhoneOS: true
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UTExportedTypeDeclarations:
          - UTTypeIdentifier: com.finanzapp.backup
            UTTypeDescription: Backup FinanzApp
            UTTypeConformsTo:
              - public.plain-text
            UTTypeTagSpecification:
              public.filename-extension:
                - finanz
        CFBundleURLTypes:
          - CFBundleURLName: com.finanzapp.app
            CFBundleURLSchemes:
              - finanzapp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: marino.finanzapp.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: FinanzApp/FinanzApp.entitlements
    entitlements:
      path: FinanzApp/FinanzApp.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.finanzapp.app
    dependencies:
      - target: FinanzAppWidget

  FinanzAppWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: FinanzAppWidget
        excludes:
          - "**/.DS_Store"
      - path: Shared
    info:
      path: FinanzAppWidget/Info.plist
      properties:
        CFBundleShortVersionString: 6.0.0
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: marino.finanzapp.app.widget
        CODE_SIGN_ENTITLEMENTS: FinanzAppWidget/FinanzAppWidget.entitlements
    entitlements:
      path: FinanzAppWidget/FinanzAppWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.finanzapp.app
    scheme:
      environmentVariables:
        _XCWidgetKind: StatsWidget
        _XCWidgetDefaultView: timeline
        _XCWidgetMaxSize: medium
